version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - .env
